"""Added password to User table

Revision ID: 5451fb7109ca
Revises: 4c972e2e5965
Create Date: 2025-11-06 17:37:58.138219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5451fb7109ca'
down_revision = '4c972e2e5965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('olid',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_password_hash')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('olid',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
